# Generated by Django 5.0.6 on 2024-07-08 18:37

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
