# Generated by Django 5.0.6 on 2024-07-08 19:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='body_markdown',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_richtext',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
